name: Documentation
on: push
jobs:
  'generate':
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream repository
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
        id: node_modules_cache

      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive --ignore-scripts

      - name: Generate documentation
        run: yarn docs

      - name: Flatten directory structure for GitHub Wiki
        run: |-
          mv docs/classes/* docs/
          mv docs/interfaces/* docs/
          rmdir docs/classes docs/interfaces
          find docs -type f -exec sed -i -e 's/\.\.\///g' -e 's/classes\///g' -e 's/interfaces\///g' {} \;

      - name: Fix link references for GitHub Wiki
        run: find docs -type f -exec sed -i 's/\.md//g' {} \;

      - name: Archive generated files
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
          retention-days: 7

  'upload':
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout wiki repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki

      - name: Cleanup old files
        run: |-
          git rm -rf . --quiet
          git reset --quiet

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: .

      - name: Check for changes
        run: >-
          git diff --exit-code --quiet
          && { echo "::set-output name=CHANGES_EXIST::false"; }
          || { echo "::set-output name=CHANGES_EXIST::true"; }
        id: git_diff

      - name: Upload documentation to GitHub Wiki
        if: steps.git_diff.outputs.CHANGES_EXIST == 'true'
        run: |-
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Changes made by $(git rev-parse --short "$GITHUB_SHA")" --quiet
          git push origin master
        env:
          repository: ${{ github.repository }}.wiki
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
